### ISSUE TITLE
problem of text overflow

### ISSUE THREAD

**Issue by shilik** [pktintali/floating_text#1]
Hi, @pktintali 
Thanks for the great plugin. I have two questions regarding the use of this plugin.
1.How to deal with the text when it is a sentence than a word? I encountered the problem of text overflow. 
Try to add an Expanded widget did get the problem solved.
2.Could you add an callback function that notify the end of the animation? If the text overflow can not be solved, I want to do an alternative approach to change to text dynamically when the animation is finished.

<img width="420" alt="Snipaste_2022-08-19_11-53-34" src="https://user-images.githubusercontent.com/1404868/185539425-3a0c47fd-1588-426e-a7e6-04863119544e.png">

**Comment by pktintali** [comment]
Thanks! @shilik
Sorry for the inconvenience.

As of now floating text is developed only considering  the single line word/sentences.
In the next update I'll definitely try to add the support for the multi-line sentences.
Coming to point 2, you did a great job by suggesting about this feature I had never thought about this, Now I think that will be really good, so wait till the next update.

One more parameter I want to add is the repeat count, If repeat is true and repeat count is not given then it'll repeat indefinitely but once repeat count is given, it'll repeat only that times.
You can expect the next update within the 2 or 3 weeks.
Have a great day.

**Comment by shilik** [comment]
Thanks very much for the quick response. I am looking forward to seeing the new features in the near future.:)

**Comment by pktintali** [comment]
New update is live 🎉
All above discussed features are implemented and bugs like text overflow and RTL are now fixed.

**Comment by shilik** [comment]
Hi,@pktintali. Great! can't wait to trying the new features!
